### ISSUE TITLE
Undefined variable: v in rssMerger.php on line 205

### ISSUE THREAD

**Issue by tryallthethings** [taophp/rss-merger#4]
Hi,

I found an undefined variable in rssMerger.php:
```
$encOri = function_exists('mb_detect_encoding')?mb_detect_encoding($v):'UTF-8';
```
But $v is only declared 2 lines below.

Regards,
Stefan

**Comment by l4nj1n9** [comment]
@roots84  Thanks. It was a bad mistake.
