### ISSUE TITLE
Merge with Makesites

### ISSUE THREAD

**Issue by tracend** [taophp/rss-merger#6]
Hi guys, 

Really appreciate your work here. You took a barebones idea and turned it into a real library. 

In all honesty I neglected RSS during the 10s in favor of APIs (as most web developers) but now that privacy concerns are becoming mainstream there is reason to believe that all these decentralized technologies (like RSS) will have a resurgence in their popularity. 

Anyway, I'd like it if you could send a pull request back to the original Makesites repo and we can continue development together. 

Cheers

**Comment by tryallthethings** [comment]
Hey!

I'd love to see some more development for this. Never stopped using RSS and I was anyway going to work on this a bit more in the next weeks as some feeds don't work properly (anymore) for me.
So I'm totally fine with merging it back and go from there.

**Comment by tryallthethings** [comment]
That enthusiasm died off quickly :)

**Comment by tracend** [comment]
Thanks for the nudge :) 

Somehow I didn't get a notification on this and failed to manually check. 

Thanks again

**Comment by tracend** [comment]
Closing as Addressed.
